export type ActivityKey = 'A1' | 'A2' | 'A3' | 'A4';

export type Product = {
  id: string;
  name: string;
  price: number;
  originalPrice?: number;
  image: string;
  description: string;
  category: string;
  stock: number;
  rating: number;
  reviews: number;
};

const BASE_PATH = process.env.NEXT_PUBLIC_BASE_PATH ?? '';
const withBasePath = (p: string) => (BASE_PATH ? `${BASE_PATH}${p}` : p);
export const pac = (filename: string) => withBasePath(`/pac/${encodeURIComponent(filename)}`);

export const products: Product[] = [
  {
    id: '2',
    name: '大漆葫芦摆件',
    price: 25,
    originalPrice: 39,
    image: pac('大漆葫芦.jpg'),
    description: '大漆葫芦摆件，色泽温润，适合桌面陈设或作为礼物。',
    category: '装饰品',
    stock: 80,
    rating: 4.7,
    reviews: 156,
  },
  {
    id: '3',
    name: '大漆屏风',
    price: 12000,
    originalPrice: 15000,
    image: pac('大漆屏风.png'),
    description: '四折大漆屏风，手工绘制传统纹样，可作为室内隔断或装饰。',
    category: '家具',
    stock: 12,
    rating: 4.8,
    reviews: 6,
  },
  {
    id: '7',
    name: '大漆盲盒系列',
    price: 120,
    originalPrice: 160,
    image: pac('大漆吉祥物.jpg'),
    description: '大漆盲盒系列：单个 120 元；四个一组 450 元。适合桌面陈设与空间点缀。',
    category: '装饰品',
    stock: 200,
    rating: 4.4,
    reviews: 93,
  },
  {
    id: '8',
    name: '大漆手工扇（经典款）',
    price: 169,
    originalPrice: 199,
    image: pac('大漆手工扇.jpg'),
    description: '大漆手工扇经典款，适合日常纳凉、拍照与陈设。',
    category: '装饰品',
    stock: 80,
    rating: 4.9,
    reviews: 34,
  },
  {
    id: '9',
    name: '大漆手镯',
    price: 480,
    originalPrice: 599,
    image: pac('大漆手镯.jpg'),
    description: '手工大漆饰品，光泽细腻，佩戴舒适，适合作为日常搭配或礼赠之选。',
    category: '装饰品',
    stock: 25,
    rating: 4.3,
    reviews: 128,
  },
  {
    id: '17',
    name: '大漆手工扇（雅致款）',
    price: 15,
    originalPrice: 29,
    image: pac('大漆手工扇 1.jpg'),
    description: '手工制作大漆扇，扇面与纹理层次丰富，适合夏日纳凉与陈设。',
    category: '装饰品',
    stock: 1000,
    rating: 4.6,
    reviews: 66,
  },
  {
    id: '21',
    name: '大漆盲盒系列（四件套）',
    price: 450,
    originalPrice: 480,
    image: pac('大漆吉祥物.jpg'),
    description: '大漆盲盒系列四件套（共 4 个），适合成组陈设或礼赠。',
    category: '装饰品',
    stock: 40,
    rating: 4.6,
    reviews: 37,
  },
  {
    id: '20',
    name: 'PCB纪念卡',
    price: 15,
    originalPrice: 29,
    image: pac('PCB纪念卡.jpg'),
    description: '特别版纪念卡片，适合作为收藏或赠礼的小物。',
    category: '装饰品',
    stock: 2000,
    rating: 4.5,
    reviews: 88,
  },
  {
    id: '19',
    name: '螺钿漆盒',
    price: 5500,
    originalPrice: 6800,
    image: pac('螺钿漆盒.png'),
    description: '螺钿工艺与大漆结合的小型收纳盒，适合收纳首饰、香丸或小物件。',
    category: '家居用品',
    stock: 3,
    rating: 4.8,
    reviews: 41,
  },
  {
    id: '18',
    name: '大漆手镯（金边款）',
    price: 280,
    originalPrice: 360,
    image: pac('大漆手镯-金.png'),
    description: '大漆手镯金边款，质感高级，适合通勤与正式场合搭配。',
    category: '装饰品',
    stock: 30,
    rating: 4.7,
    reviews: 58,
  },
  {
    id: '1',
    name: '大漆茶杯',
    price: 199,
    originalPrice: 200,
    image: pac('大漆茶杯.jpg'),
    description:
      '传统大漆工艺制作，手工打磨，色泽温润，适合日常品茶与陈设。',
    category: '茶具',
    stock: 60,
    rating: 4.9,
    reviews: 89,
  },
  {
    id: '10',
    name: '大漆茶杯（款二）',
    price: 129,
    originalPrice: 159,
    image: pac('大漆茶杯1.jpg'),
    description: '大漆工艺茶杯（款二），手感细腻，适合日常品茶与陈设。',
    category: '茶具',
    stock: 100,
    rating: 4.6,
    reviews: 89,
  },
  {
    id: '11',
    name: '大漆葫芦摆件（款二）',
    price: 59,
    originalPrice: 89,
    image: pac('大漆葫芦1.jpg'),
    description: '大漆葫芦摆件（款二），小巧精致，适合作为桌面陈设或随手把玩。',
    category: '装饰品',
    stock: 300,
    rating: 4.4,
    reviews: 56,
  },
  {
    id: '12',
    name: '大漆手工扇（便携款）',
    price: 69,
    originalPrice: 99,
    image: pac('大漆手工扇1.jpg'),
    description: '大漆手工扇便携款，轻巧易携带，适合日常纳凉与随身使用。',
    category: '装饰品',
    stock: 250,
    rating: 4.2,
    reviews: 145,
  },
  {
    id: '13',
    name: '大漆桌子（款一）',
    price: 299,
    originalPrice: 359,
    image: pac('大漆桌子1.png'),
    description: '大漆工艺桌子（款一），纹理雅致，适合家居陈设与空间搭配。',
    category: '家具',
    stock: 20,
    rating: 4.8,
    reviews: 22,
  },
  {
    id: '14',
    name: '简易漆扇（经典款）',
    price: 49,
    originalPrice: 69,
    image: pac('简易漆扇.jpg'),
    description: '入门级漆扇，轻巧便携，适合日常使用与体验传统工艺。',
    category: '装饰品',
    stock: 500,
    rating: 4.2,
    reviews: 210,
  },
  {
    id: '15',
    name: '简易漆扇（升级款）',
    price: 59,
    originalPrice: 79,
    image: pac('简易漆扇1.jpg'),
    description: '升级款漆扇，纹样更精致，适合收藏或作为礼物。',
    category: '装饰品',
    stock: 350,
    rating: 4.3,
    reviews: 188,
  },
  {
    id: '16',
    name: '大漆桌子（款二）',
    price: 219,
    originalPrice: 269,
    image: pac('大漆桌子.jpg'),
    description: '大漆工艺桌子（款二），可用于摆放茶具或工艺品，提升空间氛围。',
    category: '家具',
    stock: 30,
    rating: 4.7,
    reviews: 31,
  },
  {
    id: '4',
    name: '大漆钢笔',
    price: 139,
    originalPrice: 169,
    image: pac('大漆钢笔.jpg'),
    description: '大漆工艺钢笔，光泽细腻，书写顺滑，适合作为礼品或日常使用。',
    category: '文房用品',
    stock: 80,
    rating: 4.6,
    reviews: 78,
  },
  {
    id: '5',
    name: '鸿奕漆器',
    price: 189,
    originalPrice: 200,
    image: pac('鸿奕漆器.jpg'),
    description: '8人份大漆餐具套装，包含碗、盘、筷、勺，食品级大漆涂层，安全卫生。',
    category: '餐具',
    stock: 35,
    rating: 4.7,
    reviews: 112,
  },
  {
    id: '6',
    name: '大漆散珠',
    price: 149,
    originalPrice: 179,
    image: pac('大漆散珠.jpg'),
    description: '大漆散珠，可用于手串搭配或DIY制作，质感细腻。',
    category: '装饰品',
    stock: 100,
    rating: 4.5,
    reviews: 67,
  },
];
