export type ActivityKey = 'A1' | 'A2' | 'A3' | 'A4';

export type Product = {
  id: string;
  name: string;
  price: number;
  originalPrice?: number;
  image: string;
  description: string;
  category: string;
  stock: number;
  rating: number;
  reviews: number;
};

export const products: Product[] = [
  {
    id: '1',
    name: '大漆茶具套装',
    price: 189,
    originalPrice: 200,
    image: '/pac/1.jpg',
    description: '传统大漆工艺制作，手工打磨，色泽温润，适合茶道使用。',
    category: '茶具',
    stock: 25,
    rating: 4.9,
    reviews: 89,
  },
  {
    id: '2',
    name: '大漆首饰盒',
    price: 159,
    originalPrice: 189,
    image: '/pac/2.jpg',
    description: '精美大漆首饰盒，多层设计，内置绒布隔层。',
    category: '家居用品',
    stock: 40,
    rating: 4.7,
    reviews: 156,
  },
  {
    id: '3',
    name: '大漆屏风',
    price: 179,
    originalPrice: 200,
    image: '/pac/3.jpg',
    description: '四折大漆屏风，手工绘制传统纹样，可作为室内隔断或装饰。',
    category: '家具',
    stock: 12,
    rating: 4.8,
    reviews: 45,
  },
  {
    id: '4',
    name: '大漆文房四宝',
    price: 139,
    originalPrice: 169,
    image: '/pac/4.jpg',
    description: '包含大漆笔筒、砚台、笔架等，传统文人雅士必备。',
    category: '文房用品',
    stock: 30,
    rating: 4.6,
    reviews: 78,
  },
  {
    id: '5',
    name: '鸿奕漆器',
    price: 189,
    originalPrice: 200,
    image: '/pac/5.jpg',
    description: '大漆工艺精美漆器，适合收藏与日用。',
    category: '餐具',
    stock: 35,
    rating: 4.7,
    reviews: 112,
  },
  {
    id: '6',
    name: '大漆散珠',
    price: 149,
    originalPrice: 179,
    image: '/pac/6.jpg',
    description: '大漆工艺散珠配件，可用于手作串饰。',
    category: '配饰',
    stock: 28,
    rating: 4.5,
    reviews: 67,
  },
  {
    id: '7',
    name: '简易漆扇',
    price: 99,
    originalPrice: 129,
    image: '/pac/7.jpg',
    description: '简易漆扇，适合日常携带与展示。',
    category: '扇具',
    stock: 50,
    rating: 4.4,
    reviews: 93,
  },
  {
    id: '8',
    name: '大漆手工扇',
    price: 169,
    originalPrice: 199,
    image: '/pac/8.jpg',
    description: '手工漆扇，纹理独特，适合礼赠与收藏。',
    category: '扇具',
    stock: 18,
    rating: 4.9,
    reviews: 34,
  },
  {
    id: '9',
    name: '简易漆扇1',
    price: 79,
    originalPrice: 109,
    image: '/pac/9.jpg',
    description: '简易漆扇变体款式，轻便好用。',
    category: '扇具',
    stock: 60,
    rating: 4.3,
    reviews: 128,
  },
  {
    id: '10',
    name: '大漆茶杯1',
    price: 129,
    originalPrice: 159,
    image: '/pac/10.jpg',
    description: '单品大漆茶杯，适合个人品茗。',
    category: '茶具',
    stock: 42,
    rating: 4.6,
    reviews: 89,
  },
  {
    id: '11',
    name: '大漆葫芦1',
    price: 59,
    originalPrice: 89,
    image: '/pac/11.jpg',
    description: '小巧大漆葫芦摆件，寓意吉祥。',
    category: '摆件',
    stock: 75,
    rating: 4.4,
    reviews: 56,
  },
  {
    id: '12',
    name: '大漆手工扇1',
    price: 69,
    originalPrice: 99,
    image: '/pac/12.jpg',
    description: '手工漆扇轻量款，适合拍照打卡。',
    category: '扇具',
    stock: 100,
    rating: 4.2,
    reviews: 145,
  },
];
